### ISSUE TITLE
Confusion about data units

### ISSUE THREAD

**Issue by ghost** [diegommcc/digitalDLSorteR#1]
Hi DigitalDLSorter team，
I am very interested in your DigitalDLSorter, this idea deeply attracted me. When I read your paper and github code, I have two confusion and need to consult you.
(1) Your article mentions converting TCGA data to tpm as the data unit, but in your code description it mentions cpm, whether you are using cpm or tpm.
(2) I think the dimensions of bulk data and single-cell data are different. How do you ensure that your integrated pseudo-bulk expression profile is in the same order of magnitude as the real bulk data expression profile?

Picture from Digitaldlsorter: Deep-Learning on scRNA-Seq to Deconvolute Gene Expression Data
![image](https://user-images.githubusercontent.com/75767091/139586642-7737961e-7575-4a90-a6d3-764224429558.png)

Picture from https://github.com/cran/digitalDLSorteR
![image](https://user-images.githubusercontent.com/75767091/139586661-2bdc2db5-1a51-4126-9983-db1d45f4d4aa.png)

**Comment by diegommcc** [comment]
Hi, 
Thank you very much for your interest and questions. You can find the answers below:

1. In the case of TCGA data (paper results), we decided to use TPMs, but to generalize the code, we implemented CPMs since gene lengths are not always available. 
2. Regarding magnitude orders, the implemented workflow is as follows:
   - We add normalized single-cell profiles as CPMs because we want cells to contribute the same weight rather than creating biases due to sequencing depth or the fact that some cell types express more than others. 
   - Before training or evaluating the model, we calculate the logarithm of the pseudo-bulk samples and standardize them to avoid problems with magnitude orders. The same applies to actual bulk RNA-seq samples to be deconvoluted, so that the neural network will be trained on the same order of magnitude as real data.  

I hope everything is solved. If you have any other questions, don’t hesitate to ask.

**Comment by ghost** [comment]
Thank you for your professional answer
